# Generated by Django 2.2.3 on 2019-07-18 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('url', models.TextField(primary_key=True, serialize=False)),
                ('is_top_level', models.BooleanField(db_index=True, default=False)),
                ('rank', models.FloatField(default=0)),
                ('referrers', models.ManyToManyField(related_name='_link_referrers_+', to='src.Link')),
            ],
        ),
        migrations.CreateModel(
            name='Synset',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='src.Link')),
                ('title', models.TextField(db_index=True)),
                ('text', models.TextField()),
                ('open_graph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('synset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Synset')),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(db_index=True, max_length=100)),
                ('pos', models.CharField(max_length=1)),
                ('lemmas', models.ManyToManyField(to='src.Lemma')),
                ('entries', models.ManyToManyField(to='src.Entry')),
            ],
        ),
    ]
