# Generated by Django 2.2.3 on 2019-07-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('url', models.TextField(primary_key=True, serialize=False)),
                ('shouldFollow', models.BooleanField()),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('open_graph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Synset',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(db_index=True, max_length=100)),
                ('pos', models.CharField(max_length=1)),
                ('entries', models.ManyToManyField(to='src.Entry')),
                ('lemmas', models.ManyToManyField(to='src.Lemma')),
            ],
        ),
        migrations.AddField(
            model_name='lemma',
            name='synset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Synset'),
        ),
    ]
