# Generated by Django 2.2.3 on 2019-07-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('url', models.TextField(primary_key=True, serialize=False)),
                ('shouldFollow', models.BooleanField()),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('open_graph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('term', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('entries', models.ManyToManyField(to='src.Entry')),
            ],
        ),
    ]
